---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ensure-console-plugins
spec:
  schedule: {{ $.Values.configJob.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ $.Values.configJob.activeDeadlineSeconds }}
      template:
        metadata:
          name: ensure-console-plugins
        spec:
          serviceAccountName: {{ $.Values.serviceAccountName }}
          restartPolicy: OnFailure
          containers:
            - name: manage-console-plugins
              image: {{ .Values.configJob.image }}
              command:
                - timeout
                - {{ .Values.configJob.configTimeout | quote }}
                - ansible-playbook
                - -e
                - "@/values/values.json"
                - -vvv
                - /playbook/ensure_plugins.yml
              volumeMounts:
                - name: playbook-volume
                  mountPath: /playbook
                - name: config-volume
                  mountPath: /values
          volumes:
            - name: config-volume
              configMap:
                name: ensure-plugins-override
            - name: playbook-volume
              configMap:
                name: ensure-plugins-playbook
