#!/usr/bin/env ansible-playbook
---
- name: Ensure plugins for OpenShift console
  become: false
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
    ensure_plugins: []
  tasks:
    - name: See who I am
      ansible.builtin.command:
        oc whoami
      register: whoiam
      changed_when: false

    - name: Retrieve current console object
      kubernetes.core.k8s_info:
        api_version: operator.openshift.io/v1
        kind: Console
      register: console_obj
      until: console_obj.resources | length == 1
      retries: 20
      delay: 5

    - name: Retrieve current plugins
      ansible.builtin.set_fact:
        current_plugins: "{{ console_obj.resources[0].spec.plugins }}"

    - name: Calculate new plugins
      ansible.builtin.set_fact:
        new_plugins: "{{ (current_plugins + ensure_plugins) | unique() }}"

    - name: Ensure the new plugin list
      kubernetes.core.k8s:
        definition: "{{ console_obj.resources[0] | combine({'spec': { 'plugins': new_plugins }}) }}"
        state: present
      when: new_plugins != current_plugins
